module.exports = {
  collectCoverageFrom: ['src/**/*.{js,jsx,ts,tsx,mjs}'],
  moduleFileExtensions: ['js', 'jsx', 'ts', 'tsx', 'json'],
  roots: ['<rootDir>/test'],
  testPathIgnorePatterns: ['/node_modules/', '/lib/'],
  testRegex: '(/(test|__tests__)/.*(\\.|/|_)(test|spec))(\\.bs)?\\.[j|t]sx?$',
  testURL: 'http://localhost',
  transform: {
    '^.+\\.(js|ts)x?$': './jest.transformer.js',
  },
  transformIgnorePatterns: [
    // transform ES6 modules generated by BuckleScript
    // https://github.com/glennsl/bs-jest/issues/63
    '/node_modules/(?!(@.*/)?(bs-.*|reason-.*)/)(?!.+\\.bs\\.js).+\\.js$',
  ],
}
